language: cpp
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- echo "deb https://dl.bintray.com/conan/installers/conan-ubuntu-64_1_21_0.deb" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- conan install .
- cmake .
- cmake --build . --config Release
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T HelloWorld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ufgund:$BINTRAY_API_KEY "https://api.bintray.com/content/fgund/OTUS_CPP/Otus_Cpp_01/$TRAVIS_BUILD_NUMBER/HelloWorld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

